### ISSUE TITLE
HUD should be activated via a single press of the ALT key

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-hud#1]
This is MATE HUD, which provides a way to run menubar commands through `rofi`, much like the Unity 7 Heads-Up Display (HUD). It should feature in Ubuntu MATE 17.10 soon.

However, to activate it I'm using keybinder 3.0 and the Ctrl + Alt + Space binding. The Unity 7 HUD is activated via a single press of the Alt key, much like how Super key works. Would you be interested in take a look to see if MATE HUD can be update to support activation via release of the Alt key with no other keys having been pressed while Alt was depressed?

You can test on a VM running Ubuntu MATE 17.10 daily.

  * Install [Ubuntu MATE 17.10 daily](http://cdimage.ubuntu.com/ubuntu-mate/daily-live/current/) in a VM.
  * Add the Global Menu PPA and install `mate-applet-appmenu`
    * `sudo apt-add-repository ppa:ubuntu-mate-deb/global-menu`
    * `sudo apt update`
    * `sudo apt install mate-hud mate-applet-appmenu`
  * Reboot.

@vkareh Given you recent involvement I wondered if you might be able to take a look at this?

**Comment by vkareh** [comment]
@flexiondotorg, most certainly - I'll take a look at this!

**Comment by flexiondotorg** [comment]
So as discussed in Slack, just get `Alt + Super` working for now. It sounds like unpicking everything to get just `Alt` release working might be overly involved :-)

**Comment by vkareh** [comment]
@flexiondotorg - I created #2 to address this issue.

It allows the user to use `Alt_L` to open the HUD, but it causes erratic behavior when _also_ using `<Alt>` for window shortcuts. For the time being, I added a warning in the gsettings description and defaulted it to `<Super>Alt_L` as discussed. Therefore, I don't consider #2 as a fix for this.

I've traced the issue down to a section in the main event handler function of Marco, where the event window is not being detected properly for synthetic events coming from a different client, so Marco thinks it's a global shortcut, instead of a window shortcut. X wasn't really created with that use-case in mind, so the fix involves tricking the system into thinking that the event originated in a different window and that the previous grab never really happened. Compiz already does this, but the code is a huge ball of C++, so it's taking me a while to parse through all the cruft. I also suspect python-xlib is not entirely blameless, but I'd have to test the theory using a pure-C version of the global keybinder (i.e. brisk-menu).

As soon as I have a fix for Marco, I'll send it in and proceed to update a bunch of MATE programs that use global keybindings (mate-menu, brisk-menu, mate-hud). Eventually I'd like to update the keybinder library to support modifiers-as-triggers (which then means I'll have to update all those programs again, but I'll take it one step at a time until then).

Anyway, there you go :stuck_out_tongue:

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-hud/commit/55f4cf4d1d460f1309e1ff41753ad38bb28d40d9

**Comment by RaitaroH** [comment]
A little background. I am on Kde Neon here, not mate... but hey! It works. I only needed to install `mate-hud` then track down a deb file for `appmenu-gtk-module`. Everything nice and all... also manually add a call to the py script to autostart, but no problems there.

@vkareh Ok... but let's say I **DON'T** want it to be **JUST ALT**. In my case I use alt for a lot of other shortcuts and that means I need to do alt + key*2 (the 2nd press of the key actually makes the shortcut behave). Even `Alt+Tab` doesn't quite work unless double keypress. Also `Alt-L` doesn't do anything for me. I tried to add exceptions in the py file but doesn't seem to do anything.
`        whitelist = ['Return', 'Up', 'Down', 'Left', 'Right', 'Home', 'D', 'X', 'Space']` I used Alt + arrow keys to move around my desktop, alt+x to kill window, alt+z for zoom in, etc etc.

Also I did modify dpi a bit, `/ 1.5` instead because it just looks better to me like that.

**Comment by vkareh** [comment]
@RaitaroH - hah, good thing you figured that out! Also, to fix the need to use double-keys for any `Alt+foo*2` you need `mate-settings-daemon`, which since you're not running MATE it would not be there... So yeah, unless you run the `mate-settings-daemon` inside KDE (probably not recommended), you'll need to map the shortcut to something other than just `Alt_L`

**Comment by RaitaroH** [comment]
@vkareh No... I think I didn't express myself well.
+ if I have default for mate-hud `Alt` will be the shortcut key, where as `Alt_L` does not work. This will make any `Alt+key` shortcut require a double press (while alt is pressed so basically double the key)
+ if I have `<Alt>L` NOW the shortcut is actually respected and double presses are not required anymore. Interesting huh?

**Comment by vkareh** [comment]
huh, interesting... `Alt_L` is really the Left Alt, whereas `<Alt>L` is Alt with the L key pressed... so by having `Alt_L` you're saying that you can toggle the HUD by just tapping `Alt`? If so, that's the default behavior.

Since X11 does not accept modifier keys as shortcuts (Alt is a modifier key) it has very strange behavior (like needing double-key presses: Alt+key+key). We therefore have those whitelisted keys.

However, I have a feeling that `Alt`-based keybindings break without `mate-settings-daemon` in place, which allows it to work together with other MATE keybindings (those in the whitelist, really). Which seems to be your experience: mate-hud is eating up the `Alt` key and not replaying it forward to other keygrab listeners...

**Comment by RaitaroH** [comment]
@vkareh I see. I made a special shortcut that hopefully will kill mate-hud in case it crashes again. I mapped mate-hud to alt-space to avoid conflicts so hopefully that will be nice now.

**Comment by vkareh** [comment]
do let me know if it keeps crashing, especially if you can see any errors in your logs! we've discussed being able to use mate-hud in other desktop environments, so this could be useful :)

**Comment by RaitaroH** [comment]
`python3 /usr/lib/mate-hud/mate-hud 2>&1 | tee -a ~/Desktop/mate-hud.log` On it :+1:

**Comment by RaitaroH** [comment]
Oh and... the autostart does not work on it's own. I needed to add it manually.
