### ISSUE TITLE
Cache results and / or ignore subtrees with thousands of elements

### ISSUE THREAD

**Issue by CreamyCookie** [ubuntu-mate/mate-hud#31]
It seems like mate-hud recreates the whole menu tree (instead of caching it) every time. For example, in Firefox it takes about 10 seconds after pressing <kbd>Alt</kbd> for the HUD to show up. I think the most likely reason is that in my and likely many cases the menu item `Bookmarks` > `Bookmarks Toolbar` contains thousands of elements. If the results were cached and / or huge subtrees ignored, the HUD should be able to pop up immediately.

**Comment by vkareh** [comment]
@CreamyCookie - good call, I've noticed this too and I think that mate-hud can do some pre-loading of menu trees when a new app loads, then clear it when the app closes. This might be tricky to handle, so I think there could be a benefit of ignoring parts of the menu tree, or at least loading it asynchronously so that users can get a functional HUD even as things haven't fully loaded yet.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-hud/commit/d6cd57e474a8daca20ebfc70a2b9e8a44e78f22d
