### ISSUE TITLE
Use ▸ instead of » to separate menu levels in the HUD

### ISSUE THREAD

**Issue by fitojb** [ubuntu-mate/mate-hud#63]
This would be desirable in Romance languages like Catalan, Spanish and French, where we use [guillemets](https://en.wikipedia.org/wiki/Guillemet) as our first-level quotation marks, not as decorative arrows like in English. Both kind of usages can clash: for example, in French LibreOffice this menu item exists:

**Éditer » Annuler : Insérer un tableau « Tableau 1 »** 

Here it’d be desirable to use another character as separator:

**Éditer ▸ Annuler : Insérer un tableau « Tableau 1 »** 

This is the same character used in some areas in LibreOffice ([guidelines](https://wiki.documentfoundation.org/Design/Guidelines/UIWriting#Typography)), as well as in [the Mallard help system](http://projectmallard.org/1.2/mal_inline_guiseq.html).
![Captura desde 2022-04-10 18-51-19](https://user-images.githubusercontent.com/554953/162645348-da96014b-4d8f-4fb9-8f9b-7cc3720c9d48.png)
![Captura desde 2022-04-10 18-56-37](https://user-images.githubusercontent.com/554953/162645478-7a45a5fb-746e-4b08-9886-f707f1fe33dd.png)

The RTL version of ▸ is U+25C2 ◂

**Comment by twa022** [comment]
I added an option to configure the menu level separator along with some other configuration options and a settings GUI in my dev branch [https://github.com/twa022/mate-hud/tree/dev](https://github.com/twa022/mate-hud/tree/dev) if you want to give it a try. My first GTK GUI program so I'm going to work on it some more before trying to get it merged upstream.

What distro do you run? If it's arch based I could add a PKGBUILD. Otherwise if you just install manually there is a new dependency on python3-pkgconfig and optionally gir1.2-xfconf-0 for some features if you run on xfce.

**Comment by fitojb** [comment]
While having a settings UI is a definite win, I don’t think this particular issue deserved to be settable. It just needs a better default value.

**Comment by aromatic-dev** [comment]
> While having a settings UI is a definite win, I don’t think this particular issue deserved to be settable. It just needs a better default value.
Seconded.

Looking at the code, it's concatenating the ">" character in a bunch of places, then doing a string-replace. It would be better to use a global "path separator" variable that is used by all the places that need it.
